name = "buscacreci"
type = "javascript"
account_id = ""
workers_dev = true
route = "api/*"
zone_id = ""

[env.production]
name = "buscacreci-production"
route = "api/*"
zone_id = ""

[build]
command = "npm install && npm run build"
cwd = "./"
watch_paths = ["src/**/*.js"]

[build.upload]
format = "modules"
main = "./src/index.js"

# Vars de environment
[env.production.vars]
API_VERSION = "1.0"
CRECI_API_ENDPOINT = "https://api.creci.org.br"

# KV Namespaces para cache
[[kv_namespaces]]
binding = "CACHE"
id = ""
preview_id = ""
